=begin
#Rails with OpenAPI

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

require 'cgi'

module OpenapiClient
  class DefaultApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # OpenAPIスキーマとレスポンスが乖離しているAPI
    # @param [Hash] opts the optional parameters
    # @return [ApiMismatchFruitsGet200Response]
    def api_mismatch_fruits_get(opts = {})
      data, _status_code, _headers = api_mismatch_fruits_get_with_http_info(opts)
      data
    end

    # OpenAPIスキーマとレスポンスが乖離しているAPI
    # @param [Hash] opts the optional parameters
    # @return [Array<(ApiMismatchFruitsGet200Response, Integer, Hash)>] ApiMismatchFruitsGet200Response data, response status code and response headers
    def api_mismatch_fruits_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.api_mismatch_fruits_get ...'
      end
      # resource path
      local_var_path = '/api/mismatch/fruits'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'ApiMismatchFruitsGet200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"DefaultApi.api_mismatch_fruits_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#api_mismatch_fruits_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
