=begin
#Rails with OpenAPI

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ApiMismatchFruitsGet200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ApiMismatchFruitsGet200Response do
  let(:instance) { OpenapiClient::ApiMismatchFruitsGet200Response.new }

  describe 'test an instance of ApiMismatchFruitsGet200Response' do
    it 'should create an instance of ApiMismatchFruitsGet200Response' do
      expect(instance).to be_instance_of(OpenapiClient::ApiMismatchFruitsGet200Response)
    end
  end
  describe 'test attribute "tags"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["市内", "県内"])
      # validator.allowable_values.each do |value|
      #   expect { instance.tags = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "shop"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["スーパー", "産直所"])
      # validator.allowable_values.each do |value|
      #   expect { instance.shop = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "fruits"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
