=begin
#Rails with OpenAPI

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ApiMismatchFruitsGet200ResponseFruitsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ApiMismatchFruitsGet200ResponseFruitsInner do
  let(:instance) { OpenapiClient::ApiMismatchFruitsGet200ResponseFruitsInner.new }

  describe 'test an instance of ApiMismatchFruitsGet200ResponseFruitsInner' do
    it 'should create an instance of ApiMismatchFruitsGet200ResponseFruitsInner' do
      expect(instance).to be_instance_of(OpenapiClient::ApiMismatchFruitsGet200ResponseFruitsInner)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["りんご", "みかん"])
      # validator.allowable_values.each do |value|
      #   expect { instance.name = value }.not_to raise_error
      # end
    end
  end

end
